### ISSUE TITLE
TRAVIS show build error

### ISSUE THREAD

**Issue by ibnishak** [danielo515/TW5-auto-publish2gh-pages#6]
Shows the following message when I tried to build my wiki at https://ibnishak.github.io/irreverant-mudblood/#

    $:/core/modules/editor/engines/framed.js:35

	this.iframeDoc = this.iframeNode.contentWindow.document;

	                                              ^

    TypeError: Cannot read property 'document' of undefined

    at new FramedEngine ($:/core/modules/editor/engines/framed.js:35:48)

    at EditTextWidget.render ($:/core/modules/editor/factory.js:60:17)

    at $:/core/modules/widgets/widget.js:346:15

    at Object.$tw.utils.each (/home/travis/.nvm/versions/node/v7.0.0/lib/node_modules/tiddlywiki/boot/boot.js:69:12)

    at EditWidget.Widget.renderChildren ($:/core/modules/widgets/widget.js:345:12)

    at EditWidget.render ($:/core/modules/widgets/edit.js:33:7)

    at $:/core/modules/widgets/widget.js:346:15

    at Object.$tw.utils.each (/home/travis/.nvm/versions/node/v7.0.0/lib/node_modules/tiddlywiki/boot/boot.js:69:12)

    at TranscludeWidget.Widget.renderChildren ($:/core/modules/widgets/widget.js:345:12)

    at TranscludeWidget.render ($:/core/modules/widgets/transclude.js:33:7)

    The command "tiddlywiki ./*wiki --build" exited with 1.

**Comment by danielo515** [comment]
Seems that Travis is trying to emulate some kind of browser engine, which is unnecessary because tiddlywiky works fine under node. I have to investigate the cause because I don't have much expertise with Travis
